apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plataform-challenge.fullname" . }}
  labels:
{{ include "plataform-challenge.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "plataform-challenge.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      run: {{ include "plataform-challenge.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "plataform-challenge.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        run: {{ include "plataform-challenge.name" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "plataform-challenge.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.application.healthPath }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.application.healthPath }}
              port: http
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 300m
