apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "plataform-challenge.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "plataform-challenge.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    run: {{ include "plataform-challenge.name" . }}
spec:
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.targetCPUAverageUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: {{ .Values.autoscaling.targetCPUAverageUtilizationPercentage }}
          type: Utilization
      {{- end }}
      {{- if .Values.autoscaling.targetMemoryAverageUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: {{ .Values.autoscaling.targetMemoryAverageUtilizationPercentage }}
          type: Utilization
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "plataform-challenge.fullname" . }}