{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "plataform-challenge.serviceAccountName" . }}
  labels:
{{ include "plataform-challenge.labels" . | indent 4 }}
{{- end -}}
