variables:
  DOCKERFILE_PATH: "./parte1"
  DOCKER_REPOSITORY: "victoramsantos"
  IMAGE_NAME: "plataform-challenge"
  IMAGE_VERSION: "test"
  APPLICATION_PATH: "./app"

stages:
  - build
  - packing

gradle_build:
  image: java:8-jdk
  stage: build
  script:
    - echo $teste
    - cd $APPLICATION_PATH
    - ./gradlew clean build

docker_build_push:
  stage: packing
  script:
    - echo "docker build . -f $DOCKERFILE_PATH/Dockerfile -t $IMAGE_NAME:$IMAGE_VERSION"
    - echo "docker push ${DOCKER_REPOSITORY}/${IMAGE_NAME}:${IMAGE_VERSION}"
  only:
    - master
