variables:
  DOCKERFILE_PATH: "./parte1"
  DOCKER_REPOSITORY: "victoramsantos"
  IMAGE_NAME: "plataform-challenge"
  IMAGE_VERSION: "test"
  APPLICATION_PATH: "./app"
  APPLICATION_ARTIFACT: "./app/build/libs/app.jar"
  DOCKER_HOST: tcp://docker:2375

stages:
  - build
  - packing

gradle_build:
  image: java:8-jdk
  stage: build
  script:
    - cd $APPLICATION_PATH
    - ./gradlew clean build
  artifacts:
    paths:
      - $APPLICATION_ARTIFACT

docker_build_push:
  image: docker:18.09.7
  services:
    - docker:18.09.7-dind
  stage: packing
  script:
    - docker build . -f $DOCKERFILE_PATH/Dockerfile -t $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_VERSION
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_VERSION
#  only:
#    - master
