variables:
  DOCKERFILE_PATH: "./parte1"
  DOCKER_REPOSITORY: "victoramsantos"
  APPLICATION_NAME: plataform-challenge
  APPLICATION_PATH: "./app"
  APPLICATION_ARTIFACT: "./app/build/libs/app.jar"
  DOCKER_HOST: tcp://docker:2375
  HELM_CHART_PATH: "./parte1/plataform-challenge"
  TERRAFORM_PATH: "./parte2/terraform/providers/aws/stacks/deploy_env"

stages:
  - build
  - packing
  - deploy_minikube
  - build_stack

gradle_build:
  image: java:8-jdk
  stage: build
  script:
    - cd $APPLICATION_PATH
    - ./gradlew clean build
  artifacts:
    paths:
      - $APPLICATION_ARTIFACT

docker_build_push:
  image: docker:18.09.7
  services:
    - docker:18.09.7-dind
  stage: packing
  script:
    - docker build . -f $DOCKERFILE_PATH/Dockerfile -t $DOCKER_REPOSITORY/$APPLICATION_NAME:$CI_COMMIT_SHORT_SHA
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push $DOCKER_REPOSITORY/$APPLICATION_NAME:$CI_COMMIT_SHORT_SHA
    - echo "APPLICATION_IMAGE -> $DOCKER_REPOSITORY/$APPLICATION_NAME:$CI_COMMIT_SHORT_SHA"
  only:
    - master

deploy_minikube_ec2:
  stage: deploy_minikube
  tags:
    - ec2-runner
  before_script:
    - mkdir -p ~/.ssh
    - echo -e “$SSH_PRIVATE_KEY” > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - helm upgrade --install --set-string image.tag=$CI_COMMIT_SHORT_SHA $APPLICATION_NAME $HELM_CHART_PATH
    - kubectl rollout status deploy/$APPLICATION_NAME
    - minikube service $APPLICATION_NAME --url
  when: manual

rollback_minikube_ec2:
  stage: deploy_minikube
  tags:
    - ec2-runner
  script:
    - helm rollback $APPLICATION_NAME 0
  when: manual

build_stack:
  stage: build_stack
  tags:
    - ec2-runner
  script:
    - cd $TERRAFORM_PATH
    - terraform init
    - terraform apply -var appname=$APPLICATION_NAME -var ec2_port=80 -var container_port=8080 -var credential=$DOCKER_HASH -var default_image=$DOCKER_REPOSITORY/$APPLICATION_NAME:$CI_COMMIT_SHORT_SHA --auto-approve
  when: manual

destroy_stack:
  stage: build_stack
  tags:
    - ec2-runner
  script:
    - cd $TERRAFORM_PATH
    - terraform init
    - terraform destroy --auto-approve
  when: manual