variables:
  DOCKERFILE_PATH: "./parte1"
  DOCKER_REPOSITORY: "victoramsantos"
  IMAGE_NAME: "plataform-challenge"
  IMAGE_VERSION: "test"
  APPLICATION_PATH: "./app"
  DOCKER_HOST: tcp://docker:2375

#cache:
#  paths:
#    - $APPLICATION_PATH/.gradle

stages:
  - packing

#gradle_build:
#  image: java:8-jdk
#  stage: build
#  script:
#    - cd $APPLICATION_PATH
##    - ./gradlew clean build

docker_build_push:
  image: docker:18.09.7
  services:
    - docker:18.09.7-dind
  stage: packing
  script:
    - echo $TEST
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build . -f $DOCKERFILE_PATH/Dockerfile -t $IMAGE_NAME:$IMAGE_VERSION
#    - echo "docker build . -f $DOCKERFILE_PATH/Dockerfile -t $IMAGE_NAME:$IMAGE_VERSION"
    - echo "docker push ${DOCKER_REPOSITORY}/${IMAGE_NAME}:${IMAGE_VERSION}"
#  only:
#    - master
